"use client";
import { useEffect } from "react";
import "bootstrap/dist/css/bootstrap.min.css";
import '../styles/globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  useEffect(() => {
    require("bootstrap/dist/js/bootstrap.bundle.min.js");
  }, []);

  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
